# Generated by Django 5.2.12 on 2026-03-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_order_total_price_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='food_type',
            field=models.CharField(choices=[('veg', 'Veg'), ('nonveg', 'Non-Veg')], default='veg', max_length=10),
        ),
    ]
